In [11]:
import cv2
import numpy as np

# Define the 3D coordinates of the chessboard corners in the world coordinate system
chessboard_size = (9, 6)
origin_point = [7,5]
square_size = 0.047  # Assuming each square size is 1 unit
object_points = np.zeros((chessboard_size[0] * chessboard_size[1], 3), np.float32)
object_points[:,:2] = (np.mgrid[0:chessboard_size[0], 0:chessboard_size[1]].T.reshape(-1, 2) -np.array(origin_point))* square_size



# Load the image containing the chessboard
image = cv2.imread('results/chest_img.jpg')

# Convert the image to grayscale
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Find the chessboard corners
ret, corners = cv2.findChessboardCorners(gray_image, chessboard_size, None)

# Estimate the camera intrinsic parameters (assuming you have already calibrated the camera)
camera_matrix = np.array([[601.70849609375, 0, 425.7778015136719],
                          [0, 600.453125, 241.71969604492188],
                          [0, 0, 1]])

# Estimate the distortion coefficients (assuming you have already calibrated the camera)
dist_coeffs = np.array([0, 0, 0, 0, 0])

# Estimate the extrinsic matrix
retval, rvec, tvec = cv2.solvePnP(object_points, corners, camera_matrix, dist_coeffs)

# Convert the rotation vector to a rotation matrix
rotation_matrix, _ = cv2.Rodrigues(rvec)

# Create the extrinsic matrix
extrinsic_matrix = np.hstack((rotation_matrix, tvec))

print(extrinsic_matrix)

[[ 0.99872511  0.01465102 -0.04830625  0.02245928]
 [-0.01520456  0.99982266 -0.01111132 -0.08113743]
 [ 0.04813489  0.01183163  0.99877077  1.51667401]]
